process.env.SMTP_HOST = 'smtp.test.com'
process.env.SMTP_PORT = '587'
process.env.SMTP_SECURE = 'false'
process.env.SMTP_USER = 'test@test.com'
process.env.SMTP_PASS = 'testpass'
process.env.SMTP_FROM = 'no-reply@test.com'
